name: Daily Heartbeat

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update heartbeat
        run: |
          echo "Last update: $(date -u)" > heartbeat.log

      - name: Random real GitHub author
        run: |
          names=("octocat" "torvalds" "github" "vercel" "denoland" "hashicorp" "microsoft" "google" "docker" "apple" "python" "ruby" "golang" "kubernetes" "homebrew" "reactjs" "vuejs" "angular" "sindresorhus" "facebook")
          rand=$((RANDOM % ${#names[@]}))
          echo "AUTHOR_NAME=${names[$rand]}" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=${names[$rand]}@users.noreply.github.com" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config user.name "${AUTHOR_NAME}"
          git config user.email "${AUTHOR_EMAIL}"
          git add heartbeat.log
          git commit -m "chore: heartbeat by ${AUTHOR_NAME}" || echo "No changes"
          git push
