name: Daily Heartbeat

on:
  schedule:
    - cron: "* * * * *"   # chạy mỗi phút
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update heartbeat
        run: |
          echo "Last update: $(date -u)" > heartbeat.log

      - name: Random author
        run: |
          names=("dev-alpha" "dev-beta" "dev-gamma" "build-system" "scheduler-bot" "ops-service" "infra-agent" "data-sync" "release-agent" "monitor-bot" "core-sync" "pipeline-runner")
          rand=$((RANDOM % ${#names[@]}))
          echo "AUTHOR_NAME=${names[$rand]}" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=${names[$rand]}@users.noreply.github.com" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config user.name "${AUTHOR_NAME}"
          git config user.email "${AUTHOR_EMAIL}"

          git add heartbeat.log
          git commit -m "chore: heartbeat update by ${AUTHOR_NAME}" || echo "No changes"
          git push
